### ISSUE TITLE
Cannot use Type Explorer

### ISSUE THREAD

**Issue by ylazy** [SlavaRa/fdplugin-quicknavigate#140]
Hi!

I've downloaded the lastest build of QuickNavigate. After installed with the lastest beta FD (http://flashdevelop.org/downloads/builds/), I was no longer able to use Type Explorer. FD throw an Error:

![qn-error](https://cloud.githubusercontent.com/assets/6010183/15849715/1f84f976-2cbe-11e6-811a-50f1c69fba36.png)

**## The full Details of the Error here:**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value '0' is not a valid value for Interval. Interval must be greater than 0.
Parameter name: Interval
   at System.Windows.Forms.Timer.set_Interval(Int32 value)
   at QuickNavigate.Forms.TypeExplorerForm..ctor(Settings settings)
   at QuickNavigate.PluginMain.ShowTypeExplorer()
   at QuickNavigate.PluginMain.ShowTypeExplorer(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
FlashDevelop
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/FlashDevelop.exe
----------------------------------------
PluginCore
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/PluginCore.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.5420 built by: Win7SP1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AirProperties
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/AirProperties.DLL
----------------------------------------
AS2Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/AS2Context.DLL
----------------------------------------
ASCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ASCompletion.DLL
----------------------------------------
AS3Context
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/AS3Context.DLL
----------------------------------------
XMLCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/XMLCompletion.DLL
----------------------------------------
Aga
    Assembly Version: 1.7.0.1
    Win32 Version: 1.7.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Aga.DLL
----------------------------------------
ASClassWizard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ASClassWizard.DLL
----------------------------------------
BasicCompletion
    Assembly Version: 1.0.0.40318
    Win32 Version: 1.0.0.40318
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/BasicCompletion.DLL
----------------------------------------
BookmarkPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/BookmarkPanel.DLL
----------------------------------------
BridgeSettings
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/BridgeSettings.DLL
----------------------------------------
CodeAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CodeAnalyzer.DLL
----------------------------------------
CodeFormatter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CodeFormatter.DLL
----------------------------------------
Antlr3
    Assembly Version: 3.1.3.42154
    Win32 Version: 3.1.3.42154
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Antlr3.DLL
----------------------------------------
CodeRefactor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CodeRefactor.DLL
----------------------------------------
CssCompletion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/CssCompletion.DLL
----------------------------------------
DataEncoder
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/DataEncoder.DLL
----------------------------------------
fdb.j4n
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/fdb.j4n.DLL
----------------------------------------
jni4net.n-0.8.8.0
    Assembly Version: 0.8.8.0
    Win32 Version: 0.8.8.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/jni4net.n-0.8.8.0.DLL
----------------------------------------
FileExplorer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FileExplorer.DLL
----------------------------------------
FlashConnect
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashConnect.DLL
----------------------------------------
FlashDebugger
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashDebugger.DLL
----------------------------------------
FlashLogViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashLogViewer.DLL
----------------------------------------
FlashViewer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/FlashViewer.DLL
----------------------------------------
HaXeContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/HaXeContext.DLL
----------------------------------------
jni4net.n-0.8.4.0
    Assembly Version: 0.8.4.0
    Win32 Version: 0.8.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/jni4net.n-0.8.4.0.DLL
----------------------------------------
jni4net.n.w32.v20-0.8.4.0
    Assembly Version: 0.8.4.0
    Win32 Version: 0.8.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/jni4net.n.w32.v20-0.8.4.0.DLL
----------------------------------------
jni4net.n.w32.v20-0.8.8.0
    Assembly Version: 0.8.8.0
    Win32 Version: 0.8.8.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/jni4net.n.w32.v20-0.8.8.0.DLL
----------------------------------------
LayoutManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/LayoutManager.DLL
----------------------------------------
System.Design
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Design/2.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
LoomContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/LoomContext.DLL
----------------------------------------
ProjectManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ProjectManager.DLL
----------------------------------------
MacroManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/MacroManager.DLL
----------------------------------------
OutputPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/OutputPanel.DLL
----------------------------------------
PHPContext
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/PHPContext.DLL
----------------------------------------
SwfOp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/SwfOp.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
ResultsPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/ResultsPanel.DLL
----------------------------------------
SourceControl
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/SourceControl.DLL
----------------------------------------
StartPage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/StartPage.DLL
----------------------------------------
System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_32/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
TaskListPanel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FlashDevelop/Plugins/TaskListPanel.DLL
----------------------------------------
CompactMax
    Assembly Version: 0.1.1.28200
    Win32 Version: 0.1.1.28200
    CodeBase: file:///C:/Users/manhnm/AppData/Local/FlashDevelop/Plugins/CompactMax.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
QuickNavigate
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/manhnm/AppData/Local/FlashDevelop/Plugins/QuickNavigate.dll
----------------------------------------
o_5ee3qb
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
lqjlbv6b
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
jztyalg7
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ble11cqv
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
d6n4-gpe
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
aumcmks6
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
jxdmoxfr
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
andktynp
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
p6_cgpp-
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
hcqna9tq
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
42q6r41p
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
b63j9gju
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ay9h1z2d
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
gwqtiqkq
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
65p0mdpy
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
s4yabvjs
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Thanks!
Ylazy

**Comment by SlavaRa** [comment]
HI, I'll fix today

**Comment by SlavaRa** [comment]
@ylazy please try https://github.com/SlavaRa/fdplugin-quicknavigate/releases/tag/2.8.17
